{
    "openapi": "3.0.0",
    "info": {
<<<<<<< HEAD
        "title": "API Portal Berita",
        "description": "Portal Berita API Documentation",
=======
        "title": "API Documentation",
        "description": "Documentation for the Bookstore API",
        "contact": {
            "email": "admin@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apche.org/licenses/LICENSE-2.0.html"
        },
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
        "version": "1.0.0"
    },
    "servers": [
        {
<<<<<<< HEAD
            "url": "http://127.0.0.1:8000/api",
            "description": "Local server"
        },
        {
            "url": "http://staging.example.com",
            "description": "Staging server"
        },
        {
            "url": "http://example.com",
            "description": "Production server"
        }
    ],
    "paths": {
        "/pelanggan": {
            "get": {
                "tags": [
                    "Pelanggan"
                ],
                "summary": "List all pelanggan",
                "operationId": "listPelanggan",
=======
            "url": "http://localhost:8000/api",
            "description": "API Server"
        }
    ],
    "paths": {
        "/barang": {
            "get": {
                "tags": [
                    "Barang"
                ],
                "summary": "List of Barang",
                "description": "Retrieve a list of barang",
                "operationId": "listBarang",
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": true,
<<<<<<< HEAD
                                    "message": "Pelanggan retrieved successfully",
                                    "data": [
                                        {
                                            "id": 1,
                                            "nama": "Budi",
                                            "kontak": "08123456789",
                                            "alamat": "Jl. Merdeka 10"
=======
                                    "message": "Successfully retrieved barang",
                                    "data": [
                                        {
                                            "id": 1,
                                            "nama": "Mouse",
                                            "kategori_id": 2,
                                            "harga": 50000,
                                            "jumlah": 10
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
<<<<<<< HEAD
                    "Pelanggan"
                ],
                "summary": "Create a new pelanggan",
                "operationId": "createPelanggan",
=======
                    "Barang"
                ],
                "summary": "Create a new barang",
                "description": "Add a new barang to inventory",
                "operationId": "createBarang",
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "nama",
<<<<<<< HEAD
                                    "kontak",
                                    "alamat"
=======
                                    "kategori_id",
                                    "harga",
                                    "jumlah"
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                                ],
                                "properties": {
                                    "nama": {
                                        "type": "string",
<<<<<<< HEAD
                                        "example": "Siti"
                                    },
                                    "kontak": {
                                        "type": "string",
                                        "example": "081298765432"
                                    },
                                    "alamat": {
                                        "type": "string",
                                        "example": "Jl. Diponegoro 15"
=======
                                        "example": "Mouse"
                                    },
                                    "kategori_id": {
                                        "type": "integer",
                                        "example": 2
                                    },
                                    "harga": {
                                        "type": "number",
                                        "example": 50000
                                    },
                                    "jumlah": {
                                        "type": "integer",
                                        "example": 10
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
<<<<<<< HEAD
                        "description": "Pelanggan created successfully",
=======
                        "description": "Barang created successfully",
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": true,
<<<<<<< HEAD
                                    "message": "Pelanggan created successfully",
                                    "data": {
                                        "id": 2,
                                        "nama": "Siti",
                                        "kontak": "081298765432",
                                        "alamat": "Jl. Diponegoro 15"
=======
                                    "message": "Barang created successfully",
                                    "data": {
                                        "id": 3,
                                        "nama": "Mouse",
                                        "kategori_id": 2,
                                        "harga": 50000,
                                        "jumlah": 10
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
        "/pelanggan/{id}": {
            "put": {
                "tags": [
                    "Pelanggan"
                ],
                "summary": "Update existing pelanggan",
                "operationId": "updatePelanggan",
=======
        "/barang/{id}": {
            "put": {
                "tags": [
                    "Barang"
                ],
                "summary": "Update a barang",
                "description": "Update an existing barang",
                "operationId": "updateBarang",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "example": 1
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "nama": {
                                        "type": "string",
                                        "example": "Keyboard"
                                    },
                                    "kategori_id": {
                                        "type": "integer",
                                        "example": 2
                                    },
                                    "harga": {
                                        "type": "number",
                                        "example": 75000
                                    },
                                    "jumlah": {
                                        "type": "integer",
                                        "example": 5
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Barang updated successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": true,
                                    "message": "Barang updated successfully",
                                    "data": {
                                        "id": 1,
                                        "nama": "Keyboard",
                                        "kategori_id": 2,
                                        "harga": 75000,
                                        "jumlah": 5
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Barang"
                ],
                "summary": "Delete a barang",
                "description": "Delete an existing barang by ID",
                "operationId": "deleteBarang",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "example": 1
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Barang deleted successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": true,
                                    "message": "Barang deleted successfully"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/category": {
            "get": {
                "tags": [
                    "Category"
                ],
                "summary": "List of Categories",
                "description": "Retrieve a list of book categories",
                "operationId": "listCategory",
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": true,
                                    "message": "Successfully retrieved categories",
                                    "data": [
                                        {
                                            "id": 1,
                                            "name": "Fiction"
                                        },
                                        {
                                            "id": 2,
                                            "name": "Non-Fiction"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Category"
                ],
                "summary": "Create a new category",
                "description": "Add a new book category",
                "operationId": "createCategory",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "name"
                                ],
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "example": "Science"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Category created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": true,
                                    "message": "Category created successfully",
                                    "data": {
                                        "id": 3,
                                        "name": "Science"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/category/{id}": {
            "put": {
                "tags": [
                    "Category"
                ],
                "summary": "Update a category",
                "description": "Update a book category by ID",
                "operationId": "updateCategory",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "example": 1
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "name"
                                ],
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "example": "Updated Fiction"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Category updated successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": true,
                                    "message": "Category updated successfully",
                                    "data": {
                                        "id": 1,
                                        "name": "Updated Fiction"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Category"
                ],
                "summary": "Delete a category",
                "description": "Delete a book category by ID",
                "operationId": "deleteCategory",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "example": 1
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Category deleted successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": true,
                                    "message": "Category deleted successfully"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/transaksi-keluar": {
            "get": {
                "tags": [
                    "Transaksi Keluar"
                ],
                "summary": "List of Transaksi Keluar",
                "description": "Retrieve a list of transaksi keluar",
                "operationId": "listTransaksiKeluar",
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": true,
                                    "message": "Successfully retrieved transaksi keluar",
                                    "data": [
                                        {
                                            "id": 1,
                                            "barang_id": 2,
                                            "supplier_id": 1,
                                            "tanggal": "2024-04-30",
                                            "jumlah": 5,
                                            "harga_jual": 100000
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Transaksi Keluar"
                ],
                "summary": "Create a new transaksi keluar",
                "description": "Add a new transaksi keluar record",
                "operationId": "createTransaksiKeluar",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "barang_id",
                                    "supplier_id",
                                    "tanggal",
                                    "jumlah",
                                    "harga_jual"
                                ],
                                "properties": {
                                    "barang_id": {
                                        "type": "integer",
                                        "example": 2
                                    },
                                    "supplier_id": {
                                        "type": "integer",
                                        "example": 1
                                    },
                                    "tanggal": {
                                        "type": "string",
                                        "format": "date",
                                        "example": "2024-04-30"
                                    },
                                    "jumlah": {
                                        "type": "integer",
                                        "example": 5
                                    },
                                    "harga_jual": {
                                        "type": "number",
                                        "example": 100000
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Transaksi Keluar created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": true,
                                    "message": "Transaksi Keluar created successfully",
                                    "data": {
                                        "id": 1,
                                        "barang_id": 2,
                                        "supplier_id": 1,
                                        "tanggal": "2024-04-30",
                                        "jumlah": 5,
                                        "harga_jual": 100000
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/transaksi-keluar/{id}": {
            "put": {
                "tags": [
                    "Transaksi Keluar"
                ],
                "summary": "Update a transaksi keluar",
                "description": "Update an existing transaksi keluar",
                "operationId": "updateTransaksiKeluar",
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "example": 1
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
<<<<<<< HEAD
                                    "nama": {
                                        "type": "string",
                                        "example": "Andi"
                                    },
                                    "kontak": {
                                        "type": "string",
                                        "example": "081234000000"
                                    },
                                    "alamat": {
                                        "type": "string",
                                        "example": "Jl. Sudirman 23"
=======
                                    "barang_id": {
                                        "type": "integer",
                                        "example": 3
                                    },
                                    "supplier_id": {
                                        "type": "integer",
                                        "example": 2
                                    },
                                    "tanggal": {
                                        "type": "string",
                                        "format": "date",
                                        "example": "2024-05-01"
                                    },
                                    "jumlah": {
                                        "type": "integer",
                                        "example": 10
                                    },
                                    "harga_jual": {
                                        "type": "number",
                                        "example": 120000
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "Pelanggan updated successfully",
=======
                        "description": "Transaksi Keluar updated successfully",
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": true,
<<<<<<< HEAD
                                    "message": "Pelanggan updated successfully",
                                    "data": {
                                        "id": 1,
                                        "nama": "Andi",
                                        "kontak": "081234000000",
                                        "alamat": "Jl. Sudirman 23"
=======
                                    "message": "Transaksi Keluar updated successfully",
                                    "data": {
                                        "id": 1,
                                        "barang_id": 3,
                                        "supplier_id": 2,
                                        "tanggal": "2024-05-01",
                                        "jumlah": 10,
                                        "harga_jual": 120000
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
<<<<<<< HEAD
                    "Pelanggan"
                ],
                "summary": "Delete a pelanggan",
                "operationId": "deletePelanggan",
=======
                    "Transaksi Keluar"
                ],
                "summary": "Delete a transaksi keluar",
                "description": "Delete a transaksi keluar record by ID",
                "operationId": "deleteTransaksiKeluar",
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "example": 1
                        }
                    }
                ],
                "responses": {
                    "200": {
<<<<<<< HEAD
                        "description": "Pelanggan deleted successfully",
=======
                        "description": "Transaksi Keluar deleted successfully",
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": true,
<<<<<<< HEAD
                                    "message": "Pelanggan deleted successfully"
=======
                                    "message": "Transaksi Keluar deleted successfully"
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
                                }
                            }
                        }
                    }
                }
            }
        }
    },
<<<<<<< HEAD
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "name": "Authorization",
                "in": "header",
                "scheme": "bearer"
            }
        }
    },
    "tags": [
        {
            "name": "Pelanggan",
            "description": "Pelanggan"
=======
    "tags": [
        {
            "name": "Barang",
            "description": "Barang"
        },
        {
            "name": "Category",
            "description": "Category"
        },
        {
            "name": "Transaksi Keluar",
            "description": "Transaksi Keluar"
>>>>>>> 893040766baa160a46f356d1a5684097da6e2034
        }
    ]
}